### ISSUE TITLE
Delete position green after touch or visiable one time

### ISSUE THREAD

**Issue by chinhdl891** [JerboaBurrow/Particles#21]
I think this app is great, and it would be more user-friendly if you removed the green dot after clicking. I hope my contribution will help you.

**Comment by Jerboa-app** [comment]
I've included in [this pr](https://github.com/JerboaBurrow/Particles/pull/22) the option to not display the green dots etc. Which I think is what you mean @chinhdl891 thanks for the feedback!

Since a picture is easier here are some screen shots

| Showing toys  | Hiding toys |
| ------------- | ------------- |
| ![Screenshot_20231231_130800](https://github.com/JerboaBurrow/Particles/assets/84378622/3436f979-cbd5-4ab0-b0b2-76543dfb8ca4)  | ![Screenshot_20231231_130728](https://github.com/JerboaBurrow/Particles/assets/84378622/ebe4989d-053a-4765-a2e5-c9d1463bfd8d) |
